In [4]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [5]:
# Menampilkan data
df = pd.read_excel('Kelulusan Train.xlsx')
df.head(10)

,JENIS KELAMIN,STATUS MAHASISWA,UMUR,STATUS NIKAH,IPS 1,IPS 2,IPS 3,IPS 4,IPS 5,IPS 6,IPS 7,IPS 8,IPK,STATUS KELULUSAN
0,0,1,28,0,2.76,2.80,3.20,3.17,2.98,3.00,3.03,0.0,3.07,0
1,0,0,32,0,3.00,3.30,3.14,3.14,2.84,3.13,3.25,0.0,3.17,0
2,0,1,29,0,3.50,3.30,3.70,3.29,3.53,3.72,3.73,0.0,3.54,0
3,0,0,27,0,3.17,3.41,3.61,3.36,3.48,3.63,3.46,0.0,3.41,0
4,0,1,29,0,2.90,2.89,3.30,2.85,2.98,3.00,3.08,0.0,3.09,0
5,1,1,27,0,2.95,2.82,3.09,3.10,2.78,3.16,3.23,0.0,3.07,0
6,0,0,26,0,2.76,3.14,2.60,2.95,3.23,3.33,3.30,3.3,3.06,1
7,0,0,27,0,2.62,2.89,2.32,2.50,2.50,2.86,3.05,2.5,2.91,1
8,0,1,25,1,3.60,3.54,3.52,3.39,3.52,3.68,3.15,0.0,3.40,0
9,0,1,28,0,2.71,2.55,1.77,2.11,1.93,2.13,1.78,0.2,2.20,0

In [3]:
# Atribut regular
x = df.drop(['STATUS KELULUSAN'], axis=1)
x.head(10)

,JENIS KELAMIN,STATUS MAHASISWA,UMUR,STATUS NIKAH,IPS 1,IPS 2,IPS 3,IPS 4,IPS 5,IPS 6,IPS 7,IPS 8,IPK
0,0,1,28,0,2.76,2.80,3.20,3.17,2.98,3.00,3.03,0.0,3.07
1,0,0,32,0,3.00,3.30,3.14,3.14,2.84,3.13,3.25,0.0,3.17
2,0,1,29,0,3.50,3.30,3.70,3.29,3.53,3.72,3.73,0.0,3.54
3,0,0,27,0,3.17,3.41,3.61,3.36,3.48,3.63,3.46,0.0,3.41
4,0,1,29,0,2.90,2.89,3.30,2.85,2.98,3.00,3.08,0.0,3.09
5,1,1,27,0,2.95,2.82,3.09,3.10,2.78,3.16,3.23,0.0,3.07
6,0,0,26,0,2.76,3.14,2.60,2.95,3.23,3.33,3.30,3.3,3.06
7,0,0,27,0,2.62,2.89,2.32,2.50,2.50,2.86,3.05,2.5,2.91
8,0,1,25,1,3.60,3.54,3.52,3.39,3.52,3.68,3.15,0.0,3.40
9,0,1,28,0,2.71,2.55,1.77,2.11,1.93,2.13,1.78,0.2,2.20

In [6]:
# Atribut target
y = df['STATUS KELULUSAN']
y.head(10)

0    0
1    0
2    0
3    0
4    0
5    0
6    1
7    1
8    0
9    0
Name: STATUS KELULUSAN, dtype: int64

In [7]:
# Import Naive Bayes
from sklearn.naive_bayes import GaussianNB

In [8]:
# Memanggil fungsi Gaussian Naive Bayes
nbc = GaussianNB()

In [9]:
df.shape

(379, 14)

In [10]:
df.isnull()

,JENIS KELAMIN,STATUS MAHASISWA,UMUR,STATUS NIKAH,IPS 1,IPS 2,IPS 3,IPS 4,IPS 5,IPS 6,IPS 7,IPS 8,IPK,STATUS KELULUSAN
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
374,False,False,False,False,False,False,False,False,False,False,False,False,False,False
375,False,False,False,False,False,False,False,False,False,False,False,False,False,False
376,False,False,False,False,False,False,False,False,False,False,False,False,False,False
377,False,False,False,False,False,False,False,False,False,False,False,False,False,False
378,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [11]:
df.isnull().sum()

JENIS KELAMIN       0
STATUS MAHASISWA    0
UMUR                0
STATUS NIKAH        0
IPS 1               0
IPS 2               0
IPS 3               0
IPS 4               0
IPS 5               0
IPS 6               0
IPS 7               0
IPS 8               7
IPK                 3
STATUS KELULUSAN    0
dtype: int64

In [12]:
df.isnull().sum().sum()

10

## Filling Null Values

In [13]:
df2 = df.fillna(value = 0)
df2

,JENIS KELAMIN,STATUS MAHASISWA,UMUR,STATUS NIKAH,IPS 1,IPS 2,IPS 3,IPS 4,IPS 5,IPS 6,IPS 7,IPS 8,IPK,STATUS KELULUSAN
0,0,1,28,0,2.76,2.80,3.20,3.17,2.98,3.00,3.03,0.0,3.07,0
1,0,0,32,0,3.00,3.30,3.14,3.14,2.84,3.13,3.25,0.0,3.17,0
2,0,1,29,0,3.50,3.30,3.70,3.29,3.53,3.72,3.73,0.0,3.54,0
3,0,0,27,0,3.17,3.41,3.61,3.36,3.48,3.63,3.46,0.0,3.41,0
4,0,1,29,0,2.90,2.89,3.30,2.85,2.98,3.00,3.08,0.0,3.09,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
374,1,0,23,0,1.98,2.50,2.14,2.77,2.61,2.93,2.82,2.5,0.99,1
375,0,1,23,0,2.74,2.75,2.55,3.00,2.98,2.80,3.14,3.0,2.97,1
376,0,0,23,0,2.74,2.75,2.55,3.00,2.98,2.80,3.14,3.0,3.03,1
377,0,0,23,0,3.02,2.94,3.25,2.87,3.00,2.94,3.09,3.0,3.16,1
378,1,0,23,0,3.10,3.06,3.00,3.23,2.79,3.00,2.41,3.0,2.16,1

In [14]:
df2.isnull().sum().sum()

0

In [15]:
# Atribut regular
x = df2.drop(['STATUS KELULUSAN'], axis=1)
x.head(10)

,JENIS KELAMIN,STATUS MAHASISWA,UMUR,STATUS NIKAH,IPS 1,IPS 2,IPS 3,IPS 4,IPS 5,IPS 6,IPS 7,IPS 8,IPK
0,0,1,28,0,2.76,2.80,3.20,3.17,2.98,3.00,3.03,0.0,3.07
1,0,0,32,0,3.00,3.30,3.14,3.14,2.84,3.13,3.25,0.0,3.17
2,0,1,29,0,3.50,3.30,3.70,3.29,3.53,3.72,3.73,0.0,3.54
3,0,0,27,0,3.17,3.41,3.61,3.36,3.48,3.63,3.46,0.0,3.41
4,0,1,29,0,2.90,2.89,3.30,2.85,2.98,3.00,3.08,0.0,3.09
5,1,1,27,0,2.95,2.82,3.09,3.10,2.78,3.16,3.23,0.0,3.07
6,0,0,26,0,2.76,3.14,2.60,2.95,3.23,3.33,3.30,3.3,3.06
7,0,0,27,0,2.62,2.89,2.32,2.50,2.50,2.86,3.05,2.5,2.91
8,0,1,25,1,3.60,3.54,3.52,3.39,3.52,3.68,3.15,0.0,3.40
9,0,1,28,0,2.71,2.55,1.77,2.11,1.93,2.13,1.78,0.2,2.20

In [16]:
# Atribut target
y = df2['STATUS KELULUSAN']
y.head(10)

0    0
1    0
2    0
3    0
4    0
5    0
6    1
7    1
8    0
9    0
Name: STATUS KELULUSAN, dtype: int64

In [17]:
# Memasukkan data training pada fungsi klasifikasi Naive Bayes
data_training = nbc.fit(x,y)

In [18]:
# Prediksi pada data training
y_predict = data_training.predict(x)
print(y_predict)

[0 1 0 1 0 0 1 1 0 0 0 0 0 0 1 1 1 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 1 1 1 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 1 0 1 1 1 1 0 0 1 1 0 1 0 0
 0 0 1 1 0 1 1 1 0 0 0 1 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0
 0 1 0 1 1 1 0 1 0 0 0 0 1 1 0 0 0 1 1 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 0 1 1
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0 1 1 1 1 0 0 1 0 0 0 1 0 1 0 1 1
 1 1 1 1 1 0 0 0 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1
 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1
 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1
 1 1 1 1 1 0 1 1 1]

In [19]:
# Prediksi data testing yang akan diprediksi
JENIS_KELAMIN = 1 #pria
STATUS_MAHASISWA = 0 #mahasiswa
UMUR = 25
STATUS_NIKAH = 1 #menikah
IPS1 = 3.12
IPS2 = 2.75
IPS3 = 2.05
IPS4 = 3.01
IPS5 = 2.56
IPS6 = 3.67
IPS7 = 2.75
IPS8 = 3.45
IPK = np.average ([IPS1, IPS2, IPS3, IPS4, IPS5, IPS6, IPS7, IPS8])
data_testing = [[JENIS_KELAMIN, STATUS_MAHASISWA, UMUR, STATUS_NIKAH, IPS1, IPS2, IPS3, IPS4, IPS5, IPS6, IPS7, IPS8, IPK]]

In [20]:
# Prediksi
y_pred = data_training.predict(data_testing)

C:\Users\ALIYA NURAINI\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(

In [21]:
if y_pred == 0:
    hasil = 'Terlambat'
elif y_pred == 1:
    hasil = 'Tepat'
else:
    hasil = 'Error'
print('Hasil Prediksi Kelulusan Mahasiswa =', hasil)

Hasil Prediksi Kelulusan Mahasiswa = Terlambat

In [22]:
# Akurasi model
from sklearn.metrics import accuracy_score
print('Nilai Akurasi = %0.2f' % accuracy_score(y, y_predict))

Nilai Akurasi = 0.89

In [24]:
# Hasil
from sklearn.metrics import classification_report
print(classification_report(y, y_predict))

              precision    recall  f1-score   support

           0       0.88      0.85      0.87       163
           1       0.89      0.91      0.90       216

    accuracy                           0.89       379
   macro avg       0.89      0.88      0.88       379
weighted avg       0.89      0.89      0.89       379